### ISSUE TITLE
NoMethodError in Milia::RegistrationsController#create

### ISSUE THREAD

**Issue by hermanomark** [jekuno/milia#85]
When signing-up as a new user it returns this error NoMethodError in Milia::RegistrationsController#create

Code:
**member.rb**
```
class Member < ApplicationRecord

  belongs_to :user
  acts_as_tenant

  DEFAULT_ADMIN = {
    first_name: "Admin",
    last_name:  "Please edit me"
  }

  def self.create_new_member(user, params)
    # add any other initialization for a new member
    return user.create_member( params )
  end

  def self.create_org_admin(user)
    new_member = create_new_member(user, DEFAULT_ADMIN)
    unless new_member.errors.empty?
      raise ArgumentError, new_member.errors.full_messages.uniq.join(", ")
    end

    return new_member

  end

end
```
**tenant.rb**
```
class Tenant < ApplicationRecord

  acts_as_universal_and_determines_tenant
  has_many :members, dependent: :destroy
  validates_uniqueness_of :name
  validates_presence_of :name

    def self.create_new_tenant(tenant_params, user_params, coupon_params)

      tenant = Tenant.new(tenant_params)

      if new_signups_not_permitted?(coupon_params)

        raise ::Milia::Control::MaxTenantExceeded, "Sorry, new accounts not permitted at this time" 

      else 
        tenant.save    # create the tenant
      end
      return tenant
    end

  # ------------------------------------------------------------------------
  # new_signups_not_permitted? -- returns true if no further signups allowed
  # args: params from user input; might contain a special 'coupon' code
  #       used to determine whether or not to allow another signup
  # ------------------------------------------------------------------------
  def self.new_signups_not_permitted?(params)
    return false
  end

  # ------------------------------------------------------------------------
  # tenant_signup -- setup a new tenant in the system
  # CALLBACK from devise RegistrationsController (milia override)
  # AFTER user creation and current_tenant established
  # args:
  #   user  -- new user  obj
  #   tenant -- new tenant obj
  #   other  -- any other parameter string from initial request
  # ------------------------------------------------------------------------
    def self.tenant_signup(user, tenant, other = nil)
      #  StartupJob.queue_startup( tenant, user, other )
      # any special seeding required for a new organizational tenant
      #
      Member.create_org_admin(user)
      #
    end


end
```

**devise_permitted_parameters.rb**
```
module DevisePermittedParameters
    extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameters
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up,        keys: [:email, :password, :password_confirmation])
        devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password])

    end

end

DeviseController.send :include, DevisePermittedParameters
```

**Displayed error in terminal**
```
User Create (18.7ms)  INSERT INTO "users" ("email", "encrypted_password", "confirmation_token", "confirmation_sent_at", "skip_confirm_change_password", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["email", "user1@app.com"], ["encrypted_password", "$2a$11$f6okeOqOIxu01xp7aeE0auMRaprES5iMW/Ehrckf7SAx/Tgk7EAwa"], ["confirmation_token", "PcspHdmrpG_xkpHpvTZm"], ["confirmation_sent_at", "2018-10-07 00:23:18.014142"], ["skip_confirm_change_password", true], ["created_at", "2018-10-07 00:23:18.013556"], ["updated_at", "2018-10-07 00:23:18.013556"]]
  ↳ /home/hermanomark/.rvm/gems/ruby-2.4.1/gems/activerecord-5.2.1/lib/active_record/log_subscriber.rb:98
MILIA >>>>> [register user/org] devise: signup user success - 
Redirected to http://localhost:3000/
MILIA >>>>> [register user/org] signup user/tenant success - 
   (2.3ms)  ROLLBACK
  ↳ /home/hermanomark/.rvm/gems/ruby-2.4.1/gems/activerecord-5.2.1/lib/active_record/log_subscriber.rb:98
Completed 500 Internal Server Error in 1845ms (ActiveRecord: 242.2ms)



NoMethodError (undefined method `create_member' for #<User:0x007f3c8463b8a8>
Did you mean?  created_at):

app/models/member.rb:13:in `create_new_member'
app/models/member.rb:17:in `create_org_admin'
app/models/tenant.rb:44:in `tenant_signup'
```

I could add more necessary details if it can help about the problem. Things I've tried:

- Googling the same problem, can't find any.
- Tried restarting the server, same problem.
- Changed the line user.create_member with self.create_member?, same problem.
- Tried different emails when signing up, same problem.

Edited: Fix formatting

**Comment by hermanomark** [comment]
I manage to solve it added this lines of code in user.rb
```
acts_as_universal_and_determines_account
has_one :member, :dependent => :destroy
```

**Comment by EsterDaci** [comment]
> I manage to solve it added this lines of code in user.rb
> 
> ```
> acts_as_universal_and_determines_account
> has_one :member, :dependent => :destroy
> ```

you helped me a lot, thank you

**Comment by dineshshekhawat** [comment]
> I manage to solve it added this lines of code in user.rb
> 
> ```
> acts_as_universal_and_determines_account
> has_one :member, :dependent => :destroy
> ```

Thanks this worked for me
